#!/bin/bash

if [ "$#" -ne 2 ]
    then
    echo "usage: $0 docker-image path-to-directory"
    exit 1
fi

./stat/extract $1 $2

python3 ./stat/readFile.py $2 | ./stat/statGen >> report

rm -rf $2
docker rmi $1
